name: BlocksConverter
version: 2.2.3
api: 5.0.0
author: matcracker, JonasWindmann
main: matcracker\BlocksConverter\Loader

permissions:
    blocksconverter.commands:
        description: Allows using all plugin commands
        default: op
    blocksconverter.command.convertqueue:
        description: Allows using /convertqueue command.
        default: op
    blocksconverter.command.convert:
        description: Allows using /convert command.
        default: op
    blocksconverter.command.toolblock:
        description: Allows using /toolblock command.
        default: op